name: CI Tests

on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "14"
          - "16"
          - "18"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm i -g npm@8.16
      - run: npm ci
      - run: npm test
      - run: npm outdated
        continue-on-error: true

  check-package-lock:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm i -g npm@8.16
      - run: npm install --package-lock-only --ignore-scripts
      - run: "git diff --exit-code -- package-lock.json || (echo 'Error: package-lock.json is changed during npm install! Please make sure to use npm >= 6.9.0 and commit package-lock.json.' && false)"
